### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by wangzeyu135798** [ariG23498/G-SimCLR#11]
How to run this code?

**Comment by ariG23498** [comment]
Hey @wangzeyu135798 you can download the interactive python notebook on your local system and then run them using [Jupyter 
notebook](https://jupyter.org/). One can also use a [Kaggle kernel](https://www.kaggle.com/) or a [Google Colab](https://colab.research.google.com/notebooks/empty.ipynb) to run the code. The models are hosted in the repository releases for the sake of reproducibility of the results. Hope this helps.
